### ISSUE TITLE
metaboliteIdentification.py ownData

### ISSUE THREAD

**Issue by JanZrimec** [qLSLab/GPRuler#3]
Runnin metaboliteIdentification.py with ownData : model https://onlinelibrary.wiley.com/doi/10.1111/tpj.13075, leads to the following errors:

Traceback (most recent call last):
  File "C:\Users\JanZ\Desktop\projects-active\potato-gem\docs\GPRuler\pipeline\metaboliteIdentification.py", line 43, in <module>
    df = pd.DataFrame({'Id': cId, 'Name': cName, 'KeggId': cKegg, 'ChebiId': cChebi, 'PubchemId': cPubchem, 'boundaryCondition': cBoundaryCondition, 'chemicalFormula': cChemicalFormula, 'Inchi': cInchi})
  File "C:\Users\JanZ\Anaconda3\envs\gpruler\lib\site-packages\pandas\core\frame.py", line 636, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\JanZ\Anaconda3\envs\gpruler\lib\site-packages\pandas\core\internals\construction.py", line 502, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
  File "C:\Users\JanZ\Anaconda3\envs\gpruler\lib\site-packages\pandas\core\internals\construction.py", line 120, in arrays_to_mgr
    index = _extract_index(arrays)
  File "C:\Users\JanZ\Anaconda3\envs\gpruler\lib\site-packages\pandas\core\internals\construction.py", line 664, in _extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index

Again I think this is likely due to package version inconsistencies and can be resolved by providing the package versions used for development.

**Comment by JanZrimec** [comment]
Package versions can be found in the history of the GPRuler_requirements.txt (Commits on Mar 8, 2021), which resolves above issues.

**Comment by arianccbasile** [comment]
For me editing the row 
`df = pd.DataFrame({'Id': cId, 'Name': cName, 'KeggId': cKegg, 'ChebiId': cChebi, 'PubchemId': cPubchem, 'boundaryCondition': cBoundaryCondition, 'chemicalFormula': cChemicalFormula, 'Inchi': cInchi})`

with 
`df = pd.DataFrame({'Id': [cId], 'Name': [cName], 'KeggId': [cKegg], 'ChebiId': [cChebi], 'PubchemId': [cPubchem], 'boundaryCondition': [cBoundaryCondition], 'chemicalFormula': [cChemicalFormula], 'Inchi': [cInchi]})`

solved the issue. 

Best,
Arianna
